COSMOS_DIR_DOMAIN = "cosmos.directory"
COSMOS_DIR_API = f"https://chains.{COSMOS_DIR_DOMAIN}"
COSMOS_DIR_RPC_PROXY = f"https://rpc.{COSMOS_DIR_DOMAIN}"
COSMOS_DIR_GRPC_PROXY = f"https://rpc.{COSMOS_DIR_DOMAIN}"
COSMOS_DIR_REST_PROXY = f"https://rest.{COSMOS_DIR_DOMAIN}"
KLEO_API = "https://juno-api.kleomed.es"
STAKING_CONTRACT = "juno1zqp6uh3eg09s0h24rkwukkkg3pch49g0ndc53z9l8wrvh9dhf4nsj0ur49"
